[package]
name = "casclib-sys"
version = "0.2.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
libc = "0.2.17"

[build-dependencies]
cmake = "0.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winerror", "winbase"] }